# ----------------------------------------------------------------------------------------------------
# Pipeline to deploy a Function App
# ----------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "GraphQuery"
#  See ../Docs/Create-Variable-Group.md for details
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: windows-latest
variables:
  - group: GraphQuery

# ----------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #     - 'src/Graph.Query/*'
  #   exclude: 
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'
  #     - '**/*.md'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runPsRuleScan
    displayName: Run PSRule Bicep Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
# This approach to optionally deploy QA works but it's not DRY
# ----------------------------------------------------------------------------------------------------
stages:
  - template: pipes/function-only-pipe.yml
    parameters:
      variableGroupName: 'GraphQuery'
      environments: ['DEV'] # ['DEV','QA']
      runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
      runPsRuleScan: ${{ parameters.runPsRuleScan }}
